### ISSUE TITLE
PDF Application - Navigate directly to a page

### ISSUE THREAD

**Issue by rocheston** [os-js/osjs-pdfreader-application#7]
I have a small suggestion. The PDF Application works great. Directly go to a page by typing the page number in the app. That would be nice. I have 100+ pages of PDFs loaded in file manager. It is troublesome to navigate by clicking the >. Just type 56 and the page loads at 56.

Thanks.

**Comment by andersevenrud** [comment]
I added a new field in the toolbar where you can punch in a number to navigate.

`npm update @osjs/pdfreader-application`

**Comment by rocheston** [comment]
Wow! That is awesome. You have solved every single issue I raised. OSJS What an amazing project. Thanks again, Anders. 🙏

![grab0](https://user-images.githubusercontent.com/16910669/158021067-795641a4-fae4-452e-b063-9aa50c904a67.jpg)
